### ISSUE TITLE
InstaFix (ddinstagram) not working, switch to EmbedEZ (instagramez)

### ISSUE THREAD

**Issue by SirKioi** [Kyrela/FixTweetBot#12]
Maybe change the Instagram from ddinstagram to Instagramez, it seems more reliable.
ddinstagram barely works on discord

**Comment by Kyrela** [comment]
Thanks for the report.

[InstaFix](https://github.com/Wikidepia/InstaFix) Is currently going through some issues that can be followed [here](https://github.com/Wikidepia/InstaFix/issues/130). If this issue continues, I'll change it. Hoping that it's only a temporary issue, because InstaFix offers multiple views, while EmbedEZ sadly doesn't. Will update this issue in the next days.

In the meantime, I suggest you to disable Instagram Fix, and add EmbedEZ (InstagramEZ) as a custom website fix in the bot's settings.

**Comment by Kyrela** [comment]
Seems to be fixed for now. Dev reacted pretty quickly, I will continue to monitor it a bit, and will close this issue in the next days if there is no issues.

**Comment by Kyrela** [comment]
The problem has reappeared. I'll think about changing provider.
